/* eslint-disable no-undef */
export default {
  MOVIEDB_API_KEY: process.env.REACT_APP_MOVIEDB_API_KEY,
  MOVIEDB_BEARER_TOKEN: process.env.REACT_APP_MOVIEDB_BEARER_TOKEN,
  MOVIEDB_BASE_URL: process.env.REACT_APP_MOVIEDB_BASE_URL,
  AWS_ACCESS_KEY_ID: process.env.REACT_APP_AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY: process.env.REACT_APP_AWS_SECRET_ACCESS_KEY,
  AWS_QUEUE_URL: process.env.REACT_APP_AWS_QUEUE_URL,
};
